name: Backup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 * *'

jobs:
  backup:
    runs-on: ubuntu-20.04
    steps:
      - name: Run
        run: |
          curl -LO https://github.com/sunshineplan/feh/releases/latest/download/run
          sudo chmod +x run
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
          ./run -mongo ${{ secrets.MONGO }} -server ${{ secrets.SERVER }} -account ${{ secrets.USERNAME }} \
          -password ${{ secrets.PASSWORD }} -to ${{ secrets.TO }} -tz "Asia/Shanghai" backup
