name: Backup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          sudo apt install mongodb-org-tools
          curl -LO https://github.com/sunshineplan/feh/releases/download/v1.0/run
          sudo chmod +x run
          ./run -mongo ${{ secrets.MONGO }} -account ${{ secrets.USERNAME }} -password ${{ secrets.PASSWORD }} -to ${{ secrets.TO }} backup
