name: Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: feh

      - name: Run
        run: |
          curl -LO https://github.com/sunshineplan/feh/releases/latest/download/run
          sudo chmod +x run
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
          ./run -mongo ${{ secrets.MONGO }} -tz "Asia/Shanghai" commit
          mv *.json feh/Results
          MESSAGE=$(cat message)
          cd feh
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "$MESSAGE"
          git push
