name: Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: feh

      - name: Run
        run: |
          curl -LO https://github.com/sunshineplan/feh/releases/download/v1.0/run
          sudo chmod +x run
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
          ./run -mongo ${{ secrets.MONGO }} commit
          mv *.json feh/Results
          message = $(cat ./message)
          cd feh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$message"
          git push
