name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * 1-10,25-31 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          TZ=Asia/Shanghai date
          curl -LOsS https://github.com/sunshineplan/feh/releases/latest/download/run
          sudo chmod +x run
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
          ./run -mongo ${{ secrets.MONGO }} -server ${{ secrets.SERVER }} -account ${{ secrets.USERNAME }} \
          -password ${{ secrets.PASSWORD }} -to ${{ secrets.TO }} -tz "Asia/Shanghai" update
